# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AlterField(
            model_name='puppy',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
