# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='renter',
            field=models.BooleanField(),
        ),
    ]
